### ISSUE TITLE
To-Do's

### ISSUE THREAD

**Issue by ColinMoulds** [ColinMoulds/SWAT-OS#4]
## Proposed Changes

- [ ] Function Additions to kernal.
- [ ] Update grub & simplify the boot process.
- [ ] Write clear & concise documentation.

**Comment by psarvesh** [comment]
@ColinMoulds 
What functions need to be added to the kernel? (kernal.cpp) 
Is there a makefile? 
What is the intended target hardware for this OS? (Are you running it on QEMU?)

**Comment by AbhiShingane** [comment]
@ColinMoulds 
Since 2017. I am seeing that there is no changes or enhancement is added to this project. You guys are still want to continue this project or completely stopped it. Because I wish to contribute to this project.
Can you please share some design or documentation for this project?

**Comment by AbhiShingane** [comment]
@ColinMoulds  
If you have any plan for this project, please share with me. I want to make further enhancements for this project.

**Comment by qwergle** [comment]
@AbhiShingane
It seems that this project has been abandoned. If you wish to make further enhancements, I would recommend that you fork it and make commits there.

**Comment by Priyal804** [comment]
@ColinMoulds I would like to work on this project
